kind = "web"
previewPath = "/"
title = "iatreia.gr"
version = "1.0.0"
id = "artifacts/iatreia"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23966

[services.development]
run = "pnpm --filter @workspace/iatreia run dev"

[services.env]
PORT = "23966"
BASE_PATH = "/"
